FROM node:16-alpine as build

WORKDIR /usr/src/app

COPY client/package*.json ./

RUN npm ci

COPY client/ ./

RUN npm run build

# Production stage
FROM nginx:alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
